import sys, os, re
BASE=os.path.dirname(os.path.abspath(__file__))
GB=f"{BASE}/../ref/gate_b"
def load(p):
    s=set(open(p).read().split())
    return sorted(x for x in s if re.match(r"^[A-Za-z_.][A-Za-z0-9_.]*$",x))
a11=set(load(f"{GB}/a11_bionic_exports.txt"))
b43=set(load(f"{GB}/43_libbionic_exports.txt"))
alias=load(f"{GB}/a11_alias_to_qnx.txt")
glue =load(f"{GB}/a11_need_glue.txt")
skip=set(open(os.path.join(BASE,"libgcc_impl.txt")).read().split())
skip|=set(open(os.path.join(BASE,"glue_core_impl.txt")).read().split())
glue=[x for x in glue if x not in skip]
overlap=sorted(a11 & b43)
extra_alias={"dlclose","dlerror","dladdr"}
# dlopen/dlsym MUST NOT be re-exported as shim trampolines: the resolver itself
# (resolver.c) calls the REAL QNX dlopen/dlsym from libc.so.3.  If the shim also
# defines them, ELF symbol lookup can bind the resolver's own calls back to these
# null slots -> bx 0 (ip=00000000) once libc++.so perturbs the load scope.
alias=sorted((set(alias)|extra_alias)-{"dlopen","dlsym"})

# Emit Thumb trampolines: each just calls ws1_resolver with index in r0
asm=["\t.syntax unified", "\t.arch armv7-a", "\t.thumb", "\t.fpu softvfp", "\t.text", ""]
resolver=[]
idx=0
for name in alias:
    asm += [f"\t.global {name}", f"\t.type {name}, %function", f"\t.thumb_func",
            f"{name}:",
            f"\tmovw r12, #{idx}",
            f"\tb ws1_resolver",
            f"\t.align 2", ""]
    resolver.append((idx,name,"alias"))
    idx+=1

# Glue
icu=0
for name in glue:
    if not re.match(r"^[A-Za-z_.][A-Za-z0-9_.]*$",name): continue
    asm += [f"\t.global {name}", f"\t.type {name}, %function", f"\t.thumb_func",
            f"{name}:",
            f"\tmovw r12, #{idx}",
            f"\tb ws1_resolver",
            f"\t.align 2", ""]
    resolver.append((idx,name,"glue"))
    icu+=1; idx+=1

# Overlap
for name in overlap:
    if name in skip: continue
    asm += [f"\t.global {name}", f"\t.type {name}, %function", f"\t.thumb_func",
            f"{name}:",
            f"\tmovw r12, #{idx}",
            f"\tb ws1_resolver",
            f"\t.align 2", ""]
    resolver.append((idx,name,"overlap"))
    idx+=1

# Slot definitions in .data.ws1slots (RW segment)
asm += ["\t.section .data.ws1slots,\"aw\""]
for i in range(len(resolver)):
    asm += [f"\t.global ws1_slot_{i:04d}", f"ws1_slot_{i:04d}:", "\t.word 0"]
asm += ["\t.text", ""]

open(f"{BASE}/tramps.S","w").write("\n".join(asm)+"\n")

with open(f"{BASE}/resolver_tab.c","w") as f:
    f.write("/* auto-generated by ws1/gen_tramps.py */\n")
    f.write('#include "resolver.h"\n\n')
    for i,name,kind in resolver:
        f.write(f"extern void* ws1_slot_{i:04d};\n")
    f.write(f"struct ws1_slot ws1_slots[{len(resolver)}] = {{\n")
    for i,name,kind in resolver:
        f.write(f'  {{ (void**)&ws1_slot_{i:04d}, "{name}", WS1_{kind.upper()} }},\n')
    f.write("};\n")
    f.write(f"unsigned ws1_nslots = {len(resolver)};\n")
os.makedirs(f"{BASE}/../ref/gate_b",exist_ok=True)
print(f"tramps.S: {len(asm)} lines | slots: alias={len(alias)} glue={len(glue)} overlap={len(overlap)} (A11 total {len(a11)})")
