/* auto-generated by ws1/gen_tramps.py */
extern void _Exit(void);
extern void _Unwind_Backtrace(void);
extern void _Unwind_Complete(void);
extern void _Unwind_DeleteException(void);
extern void _Unwind_GetCFA(void);
extern void _Unwind_GetDataRelBase(void);
extern void _Unwind_GetLanguageSpecificData(void);
extern void _Unwind_GetRegionStart(void);
extern void _Unwind_GetTextRelBase(void);
extern void _Unwind_RaiseException(void);
extern void _Unwind_Resume(void);
extern void _Unwind_Resume_or_Rethrow(void);
extern void _Unwind_VRS_Get(void);
extern void _Unwind_VRS_Pop(void);
extern void _Unwind_VRS_Set(void);
extern void __aeabi_idiv(void);
extern void __aeabi_idivmod(void);
extern void __aeabi_ldivmod(void);
extern void __aeabi_uidiv(void);
extern void __aeabi_uidivmod(void);
extern void __aeabi_uldivmod(void);
extern void __aeabi_unwind_cpp_pr0(void);
extern void __aeabi_unwind_cpp_pr1(void);
extern void __aeabi_unwind_cpp_pr2(void);
extern void __assert(void);
extern void __cxa_atexit(void);
extern void __cxa_finalize(void);
extern void __divdi3(void);
extern void __divsi3(void);
extern void __exit(void);
extern void __gnu_Unwind_Find_exidx(void);
extern void __gnu_ldivmod_helper(void);
extern void __gnu_uldivmod_helper(void);
extern void __gnu_unwind_frame(void);
extern void __memcpy_chk(void);
extern void __memmove_chk(void);
extern void __memset_chk(void);
extern void __popcount_tab(void);
extern void __popcountsi2(void);
extern void __progname(void);
extern void __snprintf_chk(void);
extern void __sprintf_chk(void);
extern void __stack_chk_fail(void);
extern void __stack_chk_guard(void);
extern void __strcat_chk(void);
extern void __strcpy_chk(void);
extern void __strncat_chk(void);
extern void __strncpy_chk(void);
extern void __udivdi3(void);
extern void __udivsi3(void);
extern void __vsnprintf_chk(void);
extern void __vsprintf_chk(void);
extern void _exit(void);
extern void _longjmp(void);
extern void _setjmp(void);
extern void _tolower(void);
extern void _toupper(void);
extern void abort(void);
extern void abs(void);
extern void access(void);
extern void alarm(void);
extern void at_quick_exit(void);
extern void atexit(void);
extern void atof(void);
extern void atoi(void);
extern void atol(void);
extern void atoll(void);
extern void basename(void);
extern void bcopy(void);
extern void bsearch(void);
extern void btowc(void);
extern void bzero(void);
extern void c16rtomb(void);
extern void c32rtomb(void);
extern void calloc(void);
extern void cfgetispeed(void);
extern void cfgetospeed(void);
extern void cfmakeraw(void);
extern void cfsetispeed(void);
extern void cfsetospeed(void);
extern void chmod(void);
extern void chroot(void);
extern void clearenv(void);
extern void clearerr(void);
extern void clock(void);
extern void clock_getcpuclockid(void);
extern void clock_getres(void);
extern void clock_gettime(void);
extern void clock_nanosleep(void);
extern void clock_settime(void);
extern void closedir(void);
extern void closelog(void);
extern void ctermid(void);
extern void daemon(void);
extern void dirfd(void);
extern void dirname(void);
extern void div(void);
extern void dladdr(void);
extern void dlclose(void);
extern void dlerror(void);
extern void drand48(void);
extern void dup(void);
extern void dup2(void);
extern void endgrent(void);
extern void environ(void);
extern void erand48(void);
extern void err(void);
extern void errx(void);
extern void exit(void);
extern void fchdir(void);
extern void fchmod(void);
extern void fclose(void);
extern void fcntl(void);
extern void fdatasync(void);
extern void fdopen(void);
extern void feof(void);
extern void ferror(void);
extern void fflush(void);
extern void ffs(void);
extern void fgetc(void);
extern void fgetpos(void);
extern void fgets(void);
extern void fgetwc(void);
extern void fgetws(void);
extern void fileno(void);
extern void flock(void);
extern void flockfile(void);
extern void fnmatch(void);
extern void fopen(void);
extern void fopen64(void);
extern void fpathconf(void);
extern void fprintf(void);
extern void fputc(void);
extern void fputs(void);
extern void fputwc(void);
extern void fputws(void);
extern void fread(void);
extern void free(void);
extern void freopen(void);
extern void freopen64(void);
extern void fscanf(void);
extern void fseek(void);
extern void fseeko(void);
extern void fseeko64(void);
extern void fsetpos(void);
extern void fstatvfs(void);
extern void fstatvfs64(void);
extern void fsync(void);
extern void ftell(void);
extern void ftello(void);
extern void ftello64(void);
extern void ftime(void);
extern void ftok(void);
extern void ftruncate(void);
extern void ftruncate64(void);
extern void ftrylockfile(void);
extern void ftw(void);
extern void ftw64(void);
extern void funlockfile(void);
extern void fwide(void);
extern void fwprintf(void);
extern void fwrite(void);
extern void fwscanf(void);
extern void getc(void);
extern void getc_unlocked(void);
extern void getchar(void);
extern void getchar_unlocked(void);
extern void getcwd(void);
extern void getdtablesize(void);
extern void getenv(void);
extern void getgrent(void);
extern void getgrgid_r(void);
extern void getgrnam_r(void);
extern void gethostname(void);
extern void getitimer(void);
extern void getopt(void);
extern void getopt_long(void);
extern void getopt_long_only(void);
extern void getpagesize(void);
extern void getpgid(void);
extern void getpgrp(void);
extern void getpid(void);
extern void getppid(void);
extern void getpwent(void);
extern void getrlimit(void);
extern void getrlimit64(void);
extern void getrusage(void);
extern void gets(void);
extern void getsid(void);
extern void getsubopt(void);
extern void gettid(void);
extern void gettimeofday(void);
extern void getwc(void);
extern void getwchar(void);
extern void hcreate(void);
extern void hdestroy(void);
extern void hsearch(void);
extern void htonl(void);
extern void htons(void);
extern void index(void);
extern void inet_addr(void);
extern void inet_aton(void);
extern void inet_ntop(void);
extern void inet_pton(void);
extern void initgroups(void);
extern void inotify_add_watch(void);
extern void inotify_init(void);
extern void inotify_rm_watch(void);
extern void ioctl(void);
extern void isalnum(void);
extern void isalpha(void);
extern void isascii(void);
extern void isatty(void);
extern void isblank(void);
extern void iscntrl(void);
extern void isdigit(void);
extern void isgraph(void);
extern void islower(void);
extern void isprint(void);
extern void ispunct(void);
extern void isspace(void);
extern void isupper(void);
extern void iswalnum(void);
extern void iswalpha(void);
extern void iswblank(void);
extern void iswcntrl(void);
extern void iswctype(void);
extern void iswdigit(void);
extern void iswgraph(void);
extern void iswlower(void);
extern void iswprint(void);
extern void iswpunct(void);
extern void iswspace(void);
extern void iswupper(void);
extern void iswxdigit(void);
extern void isxdigit(void);
extern void jrand48(void);
extern void kill(void);
extern void killpg(void);
extern void labs(void);
extern void lcong48(void);
extern void ldiv(void);
extern void lfind(void);
extern void link(void);
extern void llabs(void);
extern void lldiv(void);
extern void localeconv(void);
extern void lockf(void);
extern void lockf64(void);
extern void longjmp(void);
extern void lrand48(void);
extern void lsearch(void);
extern void lseek(void);
extern void lseek64(void);
extern void mallinfo(void);
extern void malloc(void);
extern void mallopt(void);
extern void mblen(void);
extern void mbrlen(void);
extern void mbrtoc16(void);
extern void mbrtoc32(void);
extern void mbrtowc(void);
extern void mbsinit(void);
extern void mbsrtowcs(void);
extern void mbstowcs(void);
extern void mbtowc(void);
extern void memalign(void);
extern void memccpy(void);
extern void memchr(void);
extern void memcpy(void);
extern void memmove(void);
extern void memset(void);
extern void mkfifo(void);
extern void mkstemp(void);
extern void mktemp(void);
extern void mlock(void);
extern void mlockall(void);
extern void mmap(void);
extern void mmap64(void);
extern void mount(void);
extern void mprotect(void);
extern void mrand48(void);
extern void msync(void);
extern void munlock(void);
extern void munlockall(void);
extern void munmap(void);
extern void nanosleep(void);
extern void nftw(void);
extern void nftw64(void);
extern void nice(void);
extern void nrand48(void);
extern void ntohl(void);
extern void ntohs(void);
extern void openlog(void);
extern void optarg(void);
extern void opterr(void);
extern void optind(void);
extern void optopt(void);
extern void optreset(void);
extern void pathconf(void);
extern void pause(void);
extern void perror(void);
extern void pipe(void);
extern void posix_fadvise(void);
extern void posix_fadvise64(void);
extern void posix_fallocate(void);
extern void posix_fallocate64(void);
extern void posix_madvise(void);
extern void posix_memalign(void);
extern void posix_spawn(void);
extern void posix_spawn_file_actions_addclose(void);
extern void posix_spawn_file_actions_adddup2(void);
extern void posix_spawn_file_actions_addopen(void);
extern void posix_spawn_file_actions_destroy(void);
extern void posix_spawn_file_actions_init(void);
extern void posix_spawnattr_destroy(void);
extern void posix_spawnattr_getflags(void);
extern void posix_spawnattr_getpgroup(void);
extern void posix_spawnattr_getschedparam(void);
extern void posix_spawnattr_getschedpolicy(void);
extern void posix_spawnattr_getsigdefault(void);
extern void posix_spawnattr_getsigmask(void);
extern void posix_spawnattr_init(void);
extern void posix_spawnattr_setflags(void);
extern void posix_spawnattr_setpgroup(void);
extern void posix_spawnattr_setschedparam(void);
extern void posix_spawnattr_setschedpolicy(void);
extern void posix_spawnattr_setsigdefault(void);
extern void posix_spawnattr_setsigmask(void);
extern void posix_spawnp(void);
extern void pread(void);
extern void pread64(void);
extern void printf(void);
extern void pthread_atfork(void);
extern void pthread_attr_destroy(void);
extern void pthread_attr_getdetachstate(void);
extern void pthread_attr_getguardsize(void);
extern void pthread_attr_getinheritsched(void);
extern void pthread_attr_getschedparam(void);
extern void pthread_attr_getschedpolicy(void);
extern void pthread_attr_getscope(void);
extern void pthread_attr_getstack(void);
extern void pthread_attr_getstackaddr(void);
extern void pthread_attr_getstacksize(void);
extern void pthread_attr_setdetachstate(void);
extern void pthread_attr_setguardsize(void);
extern void pthread_attr_setinheritsched(void);
extern void pthread_attr_setschedparam(void);
extern void pthread_attr_setschedpolicy(void);
extern void pthread_attr_setscope(void);
extern void pthread_attr_setstack(void);
extern void pthread_attr_setstackaddr(void);
extern void pthread_attr_setstacksize(void);
extern void pthread_barrier_destroy(void);
extern void pthread_barrier_init(void);
extern void pthread_barrier_wait(void);
extern void pthread_barrierattr_destroy(void);
extern void pthread_barrierattr_getpshared(void);
extern void pthread_barrierattr_init(void);
extern void pthread_barrierattr_setpshared(void);
extern void pthread_cond_broadcast(void);
extern void pthread_cond_destroy(void);
extern void pthread_cond_init(void);
extern void pthread_cond_signal(void);
extern void pthread_cond_timedwait(void);
extern void pthread_cond_wait(void);
extern void pthread_condattr_destroy(void);
extern void pthread_condattr_getclock(void);
extern void pthread_condattr_getpshared(void);
extern void pthread_condattr_init(void);
extern void pthread_condattr_setclock(void);
extern void pthread_condattr_setpshared(void);
extern void pthread_detach(void);
extern void pthread_equal(void);
extern void pthread_exit(void);
extern void pthread_getcpuclockid(void);
extern void pthread_getname_np(void);
extern void pthread_getschedparam(void);
extern void pthread_getspecific(void);
extern void pthread_join(void);
extern void pthread_key_create(void);
extern void pthread_key_delete(void);
extern void pthread_kill(void);
extern void pthread_mutex_destroy(void);
extern void pthread_mutex_init(void);
extern void pthread_mutex_lock(void);
extern void pthread_mutex_timedlock(void);
extern void pthread_mutex_trylock(void);
extern void pthread_mutex_unlock(void);
extern void pthread_mutexattr_destroy(void);
extern void pthread_mutexattr_getprotocol(void);
extern void pthread_mutexattr_getpshared(void);
extern void pthread_mutexattr_gettype(void);
extern void pthread_mutexattr_init(void);
extern void pthread_mutexattr_setprotocol(void);
extern void pthread_mutexattr_setpshared(void);
extern void pthread_mutexattr_settype(void);
extern void pthread_once(void);
extern void pthread_rwlock_destroy(void);
extern void pthread_rwlock_init(void);
extern void pthread_rwlock_rdlock(void);
extern void pthread_rwlock_timedrdlock(void);
extern void pthread_rwlock_timedwrlock(void);
extern void pthread_rwlock_tryrdlock(void);
extern void pthread_rwlock_trywrlock(void);
extern void pthread_rwlock_unlock(void);
extern void pthread_rwlock_wrlock(void);
extern void pthread_rwlockattr_destroy(void);
extern void pthread_rwlockattr_getpshared(void);
extern void pthread_rwlockattr_init(void);
extern void pthread_rwlockattr_setpshared(void);
extern void pthread_self(void);
extern void pthread_setname_np(void);
extern void pthread_setschedparam(void);
extern void pthread_setschedprio(void);
extern void pthread_setspecific(void);
extern void pthread_sigmask(void);
extern void pthread_spin_destroy(void);
extern void pthread_spin_init(void);
extern void pthread_spin_lock(void);
extern void pthread_spin_trylock(void);
extern void pthread_spin_unlock(void);
extern void putc(void);
extern void putc_unlocked(void);
extern void putchar(void);
extern void putchar_unlocked(void);
extern void putenv(void);
extern void puts(void);
extern void putwc(void);
extern void putwchar(void);
extern void pwrite(void);
extern void pwrite64(void);
extern void qsort(void);
extern void quick_exit(void);
extern void raise(void);
extern void rand(void);
extern void rand_r(void);
extern void read(void);
extern void readdir(void);
extern void readdir64(void);
extern void readdir64_r(void);
extern void readdir_r(void);
extern void readlink(void);
extern void readv(void);
extern void realloc(void);
extern void realpath(void);
extern void remove(void);
extern void rename(void);
extern void rewind(void);
extern void rewinddir(void);
extern void scanf(void);
extern void sched_get_priority_max(void);
extern void sched_get_priority_min(void);
extern void sched_getparam(void);
extern void sched_getscheduler(void);
extern void sched_rr_get_interval(void);
extern void sched_setparam(void);
extern void sched_setscheduler(void);
extern void sched_yield(void);
extern void seed48(void);
extern void seekdir(void);
extern void select(void);
extern void sem_close(void);
extern void sem_destroy(void);
extern void sem_getvalue(void);
extern void sem_init(void);
extern void sem_open(void);
extern void sem_post(void);
extern void sem_timedwait(void);
extern void sem_trywait(void);
extern void sem_unlink(void);
extern void sem_wait(void);
extern void setbuf(void);
extern void setbuffer(void);
extern void setenv(void);
extern void setgrent(void);
extern void sethostname(void);
extern void setitimer(void);
extern void setlinebuf(void);
extern void setlocale(void);
extern void setlogmask(void);
extern void setpgid(void);
extern void setpgrp(void);
extern void setpwent(void);
extern void setrlimit(void);
extern void setrlimit64(void);
extern void setsid(void);
extern void settimeofday(void);
extern void setvbuf(void);
extern void sigaction(void);
extern void sigaddset(void);
extern void sigblock(void);
extern void sigdelset(void);
extern void sigemptyset(void);
extern void sigfillset(void);
extern void sigismember(void);
extern void siglongjmp(void);
extern void signal(void);
extern void sigpause(void);
extern void sigpending(void);
extern void sigprocmask(void);
extern void sigqueue(void);
extern void sigsetjmp(void);
extern void sigsetmask(void);
extern void sigsuspend(void);
extern void sigtimedwait(void);
extern void sigwait(void);
extern void sigwaitinfo(void);
extern void sleep(void);
extern void snprintf(void);
extern void sprintf(void);
extern void srand(void);
extern void srand48(void);
extern void sscanf(void);
extern void statvfs64(void);
extern void stderr(void);
extern void stdin(void);
extern void stdout(void);
extern void strcasecmp(void);
extern void strcat(void);
extern void strchr(void);
extern void strcmp(void);
extern void strcoll(void);
extern void strcpy(void);
extern void strcspn(void);
extern void strdup(void);
extern void strerror(void);
extern void strerror_r(void);
extern void strlcat(void);
extern void strlcpy(void);
extern void strlen(void);
extern void strncasecmp(void);
extern void strncat(void);
extern void strncmp(void);
extern void strncpy(void);
extern void strnlen(void);
extern void strpbrk(void);
extern void strrchr(void);
extern void strsep(void);
extern void strsignal(void);
extern void strspn(void);
extern void strstr(void);
extern void strtod(void);
extern void strtof(void);
extern void strtoimax(void);
extern void strtok(void);
extern void strtok_r(void);
extern void strtol(void);
extern void strtold(void);
extern void strtoll(void);
extern void strtoul(void);
extern void strtoull(void);
extern void strtoumax(void);
extern void strxfrm(void);
extern void swab(void);
extern void swprintf(void);
extern void swscanf(void);
extern void symlink(void);
extern void sync(void);
extern void sys_siglist(void);
extern void sysconf(void);
extern void syslog(void);
extern void system(void);
extern void tcdrain(void);
extern void tcflow(void);
extern void tcflush(void);
extern void tcgetattr(void);
extern void tcgetpgrp(void);
extern void tcgetsid(void);
extern void tcsendbreak(void);
extern void tcsetattr(void);
extern void tcsetpgrp(void);
extern void telldir(void);
extern void tempnam(void);
extern void time(void);
extern void timer_create(void);
extern void timer_delete(void);
extern void timer_getoverrun(void);
extern void timer_gettime(void);
extern void timer_settime(void);
extern void times(void);
extern void tmpfile(void);
extern void tmpfile64(void);
extern void tmpnam(void);
extern void tolower(void);
extern void toupper(void);
extern void towctrans(void);
extern void towlower(void);
extern void towupper(void);
extern void truncate(void);
extern void truncate64(void);
extern void umask(void);
extern void umount(void);
extern void uname(void);
extern void ungetc(void);
extern void ungetwc(void);
extern void unlink(void);
extern void unsetenv(void);
extern void usleep(void);
extern void utime(void);
extern void utimes(void);
extern void valloc(void);
extern void verr(void);
extern void verrx(void);
extern void vfork(void);
extern void vfprintf(void);
extern void vfscanf(void);
extern void vfwprintf(void);
extern void vfwscanf(void);
extern void vprintf(void);
extern void vscanf(void);
extern void vsnprintf(void);
extern void vsprintf(void);
extern void vsscanf(void);
extern void vswprintf(void);
extern void vswscanf(void);
extern void vsyslog(void);
extern void vwarn(void);
extern void vwarnx(void);
extern void vwprintf(void);
extern void vwscanf(void);
extern void wait(void);
extern void wait3(void);
extern void wait4(void);
extern void waitid(void);
extern void waitpid(void);
extern void warn(void);
extern void warnx(void);
extern void wcrtomb(void);
extern void wcscat(void);
extern void wcschr(void);
extern void wcscmp(void);
extern void wcscoll(void);
extern void wcscpy(void);
extern void wcscspn(void);
extern void wcsftime(void);
extern void wcslen(void);
extern void wcsncat(void);
extern void wcsncmp(void);
extern void wcsncpy(void);
extern void wcspbrk(void);
extern void wcsrchr(void);
extern void wcsrtombs(void);
extern void wcsspn(void);
extern void wcsstr(void);
extern void wcstod(void);
extern void wcstof(void);
extern void wcstoimax(void);
extern void wcstok(void);
extern void wcstol(void);
extern void wcstold(void);
extern void wcstoll(void);
extern void wcstombs(void);
extern void wcstoul(void);
extern void wcstoull(void);
extern void wcstoumax(void);
extern void wcsxfrm(void);
extern void wctob(void);
extern void wctomb(void);
extern void wctrans(void);
extern void wctype(void);
extern void wmemchr(void);
extern void wmemcmp(void);
extern void wmemcpy(void);
extern void wmemmove(void);
extern void wmemset(void);
extern void wprintf(void);
extern void write(void);
extern void writev(void);
extern void wscanf(void);
extern void asctime(void);
extern void asctime_r(void);
extern void chdir(void);
extern void chown(void);
extern void close(void);
extern void creat(void);
extern void creat64(void);
extern void ctime(void);
extern void ctime_r(void);
extern void daylight(void);
extern void difftime(void);
extern void endpwent(void);
extern void execl(void);
extern void execle(void);
extern void execlp(void);
extern void execv(void);
extern void execve(void);
extern void execvp(void);
extern void execvpe(void);
extern void fchown(void);
extern void fork(void);
extern void fstat(void);
extern void fstat64(void);
extern void getegid(void);
extern void geteuid(void);
extern void getgid(void);
extern void getgrgid(void);
extern void getgrnam(void);
extern void getgrouplist(void);
extern void getgroups(void);
extern void getpriority(void);
extern void getpwnam(void);
extern void getpwnam_r(void);
extern void getpwuid(void);
extern void getpwuid_r(void);
extern void getuid(void);
extern void gmtime(void);
extern void gmtime_r(void);
extern void lchown(void);
extern void localtime(void);
extern void localtime_r(void);
extern void lstat(void);
extern void lstat64(void);
extern void memcmp(void);
extern void mkdir(void);
extern void mkdtemp(void);
extern void mknod(void);
extern void mktime(void);
extern void open(void);
extern void open64(void);
extern void opendir(void);
extern void poll(void);
extern void pthread_attr_init(void);
extern void pthread_create(void);
extern void rmdir(void);
extern void setegid(void);
extern void seteuid(void);
extern void setgid(void);
extern void setgroups(void);
extern void setpriority(void);
extern void setregid(void);
extern void setreuid(void);
extern void setuid(void);
extern void stat(void);
extern void stat64(void);
extern void statvfs(void);
extern void strcasestr(void);
extern void strftime(void);
extern void timegm(void);
extern void timelocal(void);
extern void timezone(void);
extern void ttyname(void);
extern void ttyname_r(void);
extern void tzname(void);
extern void tzset(void);

void *qnxb_ptrs[1545] = {
  (void *)&_Exit,
  (void *)&_Unwind_Backtrace,
  (void *)&_Unwind_Complete,
  (void *)&_Unwind_DeleteException,
  (void *)&_Unwind_GetCFA,
  (void *)&_Unwind_GetDataRelBase,
  (void *)&_Unwind_GetLanguageSpecificData,
  (void *)&_Unwind_GetRegionStart,
  (void *)&_Unwind_GetTextRelBase,
  (void *)&_Unwind_RaiseException,
  (void *)&_Unwind_Resume,
  (void *)&_Unwind_Resume_or_Rethrow,
  (void *)&_Unwind_VRS_Get,
  (void *)&_Unwind_VRS_Pop,
  (void *)&_Unwind_VRS_Set,
  (void *)&__aeabi_idiv,
  (void *)&__aeabi_idivmod,
  (void *)&__aeabi_ldivmod,
  (void *)&__aeabi_uidiv,
  (void *)&__aeabi_uidivmod,
  (void *)&__aeabi_uldivmod,
  (void *)&__aeabi_unwind_cpp_pr0,
  (void *)&__aeabi_unwind_cpp_pr1,
  (void *)&__aeabi_unwind_cpp_pr2,
  (void *)&__assert,
  (void *)&__cxa_atexit,
  (void *)&__cxa_finalize,
  (void *)&__divdi3,
  (void *)&__divsi3,
  (void *)&__exit,
  (void *)&__gnu_Unwind_Find_exidx,
  (void *)&__gnu_ldivmod_helper,
  (void *)&__gnu_uldivmod_helper,
  (void *)&__gnu_unwind_frame,
  (void *)&__memcpy_chk,
  (void *)&__memmove_chk,
  (void *)&__memset_chk,
  (void *)&__popcount_tab,
  (void *)&__popcountsi2,
  (void *)&__progname,
  (void *)&__snprintf_chk,
  (void *)&__sprintf_chk,
  (void *)&__stack_chk_fail,
  (void *)&__stack_chk_guard,
  (void *)&__strcat_chk,
  (void *)&__strcpy_chk,
  (void *)&__strncat_chk,
  (void *)&__strncpy_chk,
  (void *)&__udivdi3,
  (void *)&__udivsi3,
  (void *)&__vsnprintf_chk,
  (void *)&__vsprintf_chk,
  (void *)&_exit,
  (void *)&_longjmp,
  (void *)&_setjmp,
  (void *)&_tolower,
  (void *)&_toupper,
  (void *)&abort,
  (void *)&abs,
  (void *)&access,
  (void *)&alarm,
  (void *)&at_quick_exit,
  (void *)&atexit,
  (void *)&atof,
  (void *)&atoi,
  (void *)&atol,
  (void *)&atoll,
  (void *)&basename,
  (void *)&bcopy,
  (void *)&bsearch,
  (void *)&btowc,
  (void *)&bzero,
  (void *)&c16rtomb,
  (void *)&c32rtomb,
  (void *)&calloc,
  (void *)&cfgetispeed,
  (void *)&cfgetospeed,
  (void *)&cfmakeraw,
  (void *)&cfsetispeed,
  (void *)&cfsetospeed,
  (void *)&chmod,
  (void *)&chroot,
  (void *)&clearenv,
  (void *)&clearerr,
  (void *)&clock,
  (void *)&clock_getcpuclockid,
  (void *)&clock_getres,
  (void *)&clock_gettime,
  (void *)&clock_nanosleep,
  (void *)&clock_settime,
  (void *)&closedir,
  (void *)&closelog,
  (void *)&ctermid,
  (void *)&daemon,
  (void *)&dirfd,
  (void *)&dirname,
  (void *)&div,
  (void *)&dladdr,
  (void *)&dlclose,
  (void *)&dlerror,
  (void *)&drand48,
  (void *)&dup,
  (void *)&dup2,
  (void *)&endgrent,
  (void *)&environ,
  (void *)&erand48,
  (void *)&err,
  (void *)&errx,
  (void *)&exit,
  (void *)&fchdir,
  (void *)&fchmod,
  (void *)&fclose,
  (void *)&fcntl,
  (void *)&fdatasync,
  (void *)&fdopen,
  (void *)&feof,
  (void *)&ferror,
  (void *)&fflush,
  (void *)&ffs,
  (void *)&fgetc,
  (void *)&fgetpos,
  (void *)&fgets,
  (void *)&fgetwc,
  (void *)&fgetws,
  (void *)&fileno,
  (void *)&flock,
  (void *)&flockfile,
  (void *)&fnmatch,
  (void *)&fopen,
  (void *)&fopen64,
  (void *)&fpathconf,
  (void *)&fprintf,
  (void *)&fputc,
  (void *)&fputs,
  (void *)&fputwc,
  (void *)&fputws,
  (void *)&fread,
  (void *)&free,
  (void *)&freopen,
  (void *)&freopen64,
  (void *)&fscanf,
  (void *)&fseek,
  (void *)&fseeko,
  (void *)&fseeko64,
  (void *)&fsetpos,
  (void *)&fstatvfs,
  (void *)&fstatvfs64,
  (void *)&fsync,
  (void *)&ftell,
  (void *)&ftello,
  (void *)&ftello64,
  (void *)&ftime,
  (void *)&ftok,
  (void *)&ftruncate,
  (void *)&ftruncate64,
  (void *)&ftrylockfile,
  (void *)&ftw,
  (void *)&ftw64,
  (void *)&funlockfile,
  (void *)&fwide,
  (void *)&fwprintf,
  (void *)&fwrite,
  (void *)&fwscanf,
  (void *)&getc,
  (void *)&getc_unlocked,
  (void *)&getchar,
  (void *)&getchar_unlocked,
  (void *)&getcwd,
  (void *)&getdtablesize,
  (void *)&getenv,
  (void *)&getgrent,
  (void *)&getgrgid_r,
  (void *)&getgrnam_r,
  (void *)&gethostname,
  (void *)&getitimer,
  (void *)&getopt,
  (void *)&getopt_long,
  (void *)&getopt_long_only,
  (void *)&getpagesize,
  (void *)&getpgid,
  (void *)&getpgrp,
  (void *)&getpid,
  (void *)&getppid,
  (void *)&getpwent,
  (void *)&getrlimit,
  (void *)&getrlimit64,
  (void *)&getrusage,
  (void *)&gets,
  (void *)&getsid,
  (void *)&getsubopt,
  (void *)&gettid,
  (void *)&gettimeofday,
  (void *)&getwc,
  (void *)&getwchar,
  (void *)&hcreate,
  (void *)&hdestroy,
  (void *)&hsearch,
  (void *)&htonl,
  (void *)&htons,
  (void *)&index,
  (void *)&inet_addr,
  (void *)&inet_aton,
  (void *)&inet_ntop,
  (void *)&inet_pton,
  (void *)&initgroups,
  (void *)&inotify_add_watch,
  (void *)&inotify_init,
  (void *)&inotify_rm_watch,
  (void *)&ioctl,
  (void *)&isalnum,
  (void *)&isalpha,
  (void *)&isascii,
  (void *)&isatty,
  (void *)&isblank,
  (void *)&iscntrl,
  (void *)&isdigit,
  (void *)&isgraph,
  (void *)&islower,
  (void *)&isprint,
  (void *)&ispunct,
  (void *)&isspace,
  (void *)&isupper,
  (void *)&iswalnum,
  (void *)&iswalpha,
  (void *)&iswblank,
  (void *)&iswcntrl,
  (void *)&iswctype,
  (void *)&iswdigit,
  (void *)&iswgraph,
  (void *)&iswlower,
  (void *)&iswprint,
  (void *)&iswpunct,
  (void *)&iswspace,
  (void *)&iswupper,
  (void *)&iswxdigit,
  (void *)&isxdigit,
  (void *)&jrand48,
  (void *)&kill,
  (void *)&killpg,
  (void *)&labs,
  (void *)&lcong48,
  (void *)&ldiv,
  (void *)&lfind,
  (void *)&link,
  (void *)&llabs,
  (void *)&lldiv,
  (void *)&localeconv,
  (void *)&lockf,
  (void *)&lockf64,
  (void *)&longjmp,
  (void *)&lrand48,
  (void *)&lsearch,
  (void *)&lseek,
  (void *)&lseek64,
  (void *)&mallinfo,
  (void *)&malloc,
  (void *)&mallopt,
  (void *)&mblen,
  (void *)&mbrlen,
  (void *)&mbrtoc16,
  (void *)&mbrtoc32,
  (void *)&mbrtowc,
  (void *)&mbsinit,
  (void *)&mbsrtowcs,
  (void *)&mbstowcs,
  (void *)&mbtowc,
  (void *)&memalign,
  (void *)&memccpy,
  (void *)&memchr,
  (void *)&memcpy,
  (void *)&memmove,
  (void *)&memset,
  (void *)&mkfifo,
  (void *)&mkstemp,
  (void *)&mktemp,
  (void *)&mlock,
  (void *)&mlockall,
  (void *)&mmap,
  (void *)&mmap64,
  (void *)&mount,
  (void *)&mprotect,
  (void *)&mrand48,
  (void *)&msync,
  (void *)&munlock,
  (void *)&munlockall,
  (void *)&munmap,
  (void *)&nanosleep,
  (void *)&nftw,
  (void *)&nftw64,
  (void *)&nice,
  (void *)&nrand48,
  (void *)&ntohl,
  (void *)&ntohs,
  (void *)&openlog,
  (void *)&optarg,
  (void *)&opterr,
  (void *)&optind,
  (void *)&optopt,
  (void *)&optreset,
  (void *)&pathconf,
  (void *)&pause,
  (void *)&perror,
  (void *)&pipe,
  (void *)&posix_fadvise,
  (void *)&posix_fadvise64,
  (void *)&posix_fallocate,
  (void *)&posix_fallocate64,
  (void *)&posix_madvise,
  (void *)&posix_memalign,
  (void *)&posix_spawn,
  (void *)&posix_spawn_file_actions_addclose,
  (void *)&posix_spawn_file_actions_adddup2,
  (void *)&posix_spawn_file_actions_addopen,
  (void *)&posix_spawn_file_actions_destroy,
  (void *)&posix_spawn_file_actions_init,
  (void *)&posix_spawnattr_destroy,
  (void *)&posix_spawnattr_getflags,
  (void *)&posix_spawnattr_getpgroup,
  (void *)&posix_spawnattr_getschedparam,
  (void *)&posix_spawnattr_getschedpolicy,
  (void *)&posix_spawnattr_getsigdefault,
  (void *)&posix_spawnattr_getsigmask,
  (void *)&posix_spawnattr_init,
  (void *)&posix_spawnattr_setflags,
  (void *)&posix_spawnattr_setpgroup,
  (void *)&posix_spawnattr_setschedparam,
  (void *)&posix_spawnattr_setschedpolicy,
  (void *)&posix_spawnattr_setsigdefault,
  (void *)&posix_spawnattr_setsigmask,
  (void *)&posix_spawnp,
  (void *)&pread,
  (void *)&pread64,
  (void *)&printf,
  (void *)&pthread_atfork,
  (void *)&pthread_attr_destroy,
  (void *)&pthread_attr_getdetachstate,
  (void *)&pthread_attr_getguardsize,
  (void *)&pthread_attr_getinheritsched,
  (void *)&pthread_attr_getschedparam,
  (void *)&pthread_attr_getschedpolicy,
  (void *)&pthread_attr_getscope,
  (void *)&pthread_attr_getstack,
  (void *)&pthread_attr_getstackaddr,
  (void *)&pthread_attr_getstacksize,
  (void *)&pthread_attr_setdetachstate,
  (void *)&pthread_attr_setguardsize,
  (void *)&pthread_attr_setinheritsched,
  (void *)&pthread_attr_setschedparam,
  (void *)&pthread_attr_setschedpolicy,
  (void *)&pthread_attr_setscope,
  (void *)&pthread_attr_setstack,
  (void *)&pthread_attr_setstackaddr,
  (void *)&pthread_attr_setstacksize,
  (void *)&pthread_barrier_destroy,
  (void *)&pthread_barrier_init,
  (void *)&pthread_barrier_wait,
  (void *)&pthread_barrierattr_destroy,
  (void *)&pthread_barrierattr_getpshared,
  (void *)&pthread_barrierattr_init,
  (void *)&pthread_barrierattr_setpshared,
  (void *)&pthread_cond_broadcast,
  (void *)&pthread_cond_destroy,
  (void *)&pthread_cond_init,
  (void *)&pthread_cond_signal,
  (void *)&pthread_cond_timedwait,
  (void *)&pthread_cond_wait,
  (void *)&pthread_condattr_destroy,
  (void *)&pthread_condattr_getclock,
  (void *)&pthread_condattr_getpshared,
  (void *)&pthread_condattr_init,
  (void *)&pthread_condattr_setclock,
  (void *)&pthread_condattr_setpshared,
  (void *)&pthread_detach,
  (void *)&pthread_equal,
  (void *)&pthread_exit,
  (void *)&pthread_getcpuclockid,
  (void *)&pthread_getname_np,
  (void *)&pthread_getschedparam,
  (void *)&pthread_getspecific,
  (void *)&pthread_join,
  (void *)&pthread_key_create,
  (void *)&pthread_key_delete,
  (void *)&pthread_kill,
  (void *)&pthread_mutex_destroy,
  (void *)&pthread_mutex_init,
  (void *)&pthread_mutex_lock,
  (void *)&pthread_mutex_timedlock,
  (void *)&pthread_mutex_trylock,
  (void *)&pthread_mutex_unlock,
  (void *)&pthread_mutexattr_destroy,
  (void *)&pthread_mutexattr_getprotocol,
  (void *)&pthread_mutexattr_getpshared,
  (void *)&pthread_mutexattr_gettype,
  (void *)&pthread_mutexattr_init,
  (void *)&pthread_mutexattr_setprotocol,
  (void *)&pthread_mutexattr_setpshared,
  (void *)&pthread_mutexattr_settype,
  (void *)&pthread_once,
  (void *)&pthread_rwlock_destroy,
  (void *)&pthread_rwlock_init,
  (void *)&pthread_rwlock_rdlock,
  (void *)&pthread_rwlock_timedrdlock,
  (void *)&pthread_rwlock_timedwrlock,
  (void *)&pthread_rwlock_tryrdlock,
  (void *)&pthread_rwlock_trywrlock,
  (void *)&pthread_rwlock_unlock,
  (void *)&pthread_rwlock_wrlock,
  (void *)&pthread_rwlockattr_destroy,
  (void *)&pthread_rwlockattr_getpshared,
  (void *)&pthread_rwlockattr_init,
  (void *)&pthread_rwlockattr_setpshared,
  (void *)&pthread_self,
  (void *)&pthread_setname_np,
  (void *)&pthread_setschedparam,
  (void *)&pthread_setschedprio,
  (void *)&pthread_setspecific,
  (void *)&pthread_sigmask,
  (void *)&pthread_spin_destroy,
  (void *)&pthread_spin_init,
  (void *)&pthread_spin_lock,
  (void *)&pthread_spin_trylock,
  (void *)&pthread_spin_unlock,
  (void *)&putc,
  (void *)&putc_unlocked,
  (void *)&putchar,
  (void *)&putchar_unlocked,
  (void *)&putenv,
  (void *)&puts,
  (void *)&putwc,
  (void *)&putwchar,
  (void *)&pwrite,
  (void *)&pwrite64,
  (void *)&qsort,
  (void *)&quick_exit,
  (void *)&raise,
  (void *)&rand,
  (void *)&rand_r,
  (void *)&read,
  (void *)&readdir,
  (void *)&readdir64,
  (void *)&readdir64_r,
  (void *)&readdir_r,
  (void *)&readlink,
  (void *)&readv,
  (void *)&realloc,
  (void *)&realpath,
  (void *)&remove,
  (void *)&rename,
  (void *)&rewind,
  (void *)&rewinddir,
  (void *)&scanf,
  (void *)&sched_get_priority_max,
  (void *)&sched_get_priority_min,
  (void *)&sched_getparam,
  (void *)&sched_getscheduler,
  (void *)&sched_rr_get_interval,
  (void *)&sched_setparam,
  (void *)&sched_setscheduler,
  (void *)&sched_yield,
  (void *)&seed48,
  (void *)&seekdir,
  (void *)&select,
  (void *)&sem_close,
  (void *)&sem_destroy,
  (void *)&sem_getvalue,
  (void *)&sem_init,
  (void *)&sem_open,
  (void *)&sem_post,
  (void *)&sem_timedwait,
  (void *)&sem_trywait,
  (void *)&sem_unlink,
  (void *)&sem_wait,
  (void *)&setbuf,
  (void *)&setbuffer,
  (void *)&setenv,
  (void *)&setgrent,
  (void *)&sethostname,
  (void *)&setitimer,
  (void *)&setlinebuf,
  (void *)&setlocale,
  (void *)&setlogmask,
  (void *)&setpgid,
  (void *)&setpgrp,
  (void *)&setpwent,
  (void *)&setrlimit,
  (void *)&setrlimit64,
  (void *)&setsid,
  (void *)&settimeofday,
  (void *)&setvbuf,
  (void *)&sigaction,
  (void *)&sigaddset,
  (void *)&sigblock,
  (void *)&sigdelset,
  (void *)&sigemptyset,
  (void *)&sigfillset,
  (void *)&sigismember,
  (void *)&siglongjmp,
  (void *)&signal,
  (void *)&sigpause,
  (void *)&sigpending,
  (void *)&sigprocmask,
  (void *)&sigqueue,
  (void *)&sigsetjmp,
  (void *)&sigsetmask,
  (void *)&sigsuspend,
  (void *)&sigtimedwait,
  (void *)&sigwait,
  (void *)&sigwaitinfo,
  (void *)&sleep,
  (void *)&snprintf,
  (void *)&sprintf,
  (void *)&srand,
  (void *)&srand48,
  (void *)&sscanf,
  (void *)&statvfs64,
  (void *)&stderr,
  (void *)&stdin,
  (void *)&stdout,
  (void *)&strcasecmp,
  (void *)&strcat,
  (void *)&strchr,
  (void *)&strcmp,
  (void *)&strcoll,
  (void *)&strcpy,
  (void *)&strcspn,
  (void *)&strdup,
  (void *)&strerror,
  (void *)&strerror_r,
  (void *)&strlcat,
  (void *)&strlcpy,
  (void *)&strlen,
  (void *)&strncasecmp,
  (void *)&strncat,
  (void *)&strncmp,
  (void *)&strncpy,
  (void *)&strnlen,
  (void *)&strpbrk,
  (void *)&strrchr,
  (void *)&strsep,
  (void *)&strsignal,
  (void *)&strspn,
  (void *)&strstr,
  (void *)&strtod,
  (void *)&strtof,
  (void *)&strtoimax,
  (void *)&strtok,
  (void *)&strtok_r,
  (void *)&strtol,
  (void *)&strtold,
  (void *)&strtoll,
  (void *)&strtoul,
  (void *)&strtoull,
  (void *)&strtoumax,
  (void *)&strxfrm,
  (void *)&swab,
  (void *)&swprintf,
  (void *)&swscanf,
  (void *)&symlink,
  (void *)&sync,
  (void *)&sys_siglist,
  (void *)&sysconf,
  (void *)&syslog,
  (void *)&system,
  (void *)&tcdrain,
  (void *)&tcflow,
  (void *)&tcflush,
  (void *)&tcgetattr,
  (void *)&tcgetpgrp,
  (void *)&tcgetsid,
  (void *)&tcsendbreak,
  (void *)&tcsetattr,
  (void *)&tcsetpgrp,
  (void *)&telldir,
  (void *)&tempnam,
  (void *)&time,
  (void *)&timer_create,
  (void *)&timer_delete,
  (void *)&timer_getoverrun,
  (void *)&timer_gettime,
  (void *)&timer_settime,
  (void *)&times,
  (void *)&tmpfile,
  (void *)&tmpfile64,
  (void *)&tmpnam,
  (void *)&tolower,
  (void *)&toupper,
  (void *)&towctrans,
  (void *)&towlower,
  (void *)&towupper,
  (void *)&truncate,
  (void *)&truncate64,
  (void *)&umask,
  (void *)&umount,
  (void *)&uname,
  (void *)&ungetc,
  (void *)&ungetwc,
  (void *)&unlink,
  (void *)&unsetenv,
  (void *)&usleep,
  (void *)&utime,
  (void *)&utimes,
  (void *)&valloc,
  (void *)&verr,
  (void *)&verrx,
  (void *)&vfork,
  (void *)&vfprintf,
  (void *)&vfscanf,
  (void *)&vfwprintf,
  (void *)&vfwscanf,
  (void *)&vprintf,
  (void *)&vscanf,
  (void *)&vsnprintf,
  (void *)&vsprintf,
  (void *)&vsscanf,
  (void *)&vswprintf,
  (void *)&vswscanf,
  (void *)&vsyslog,
  (void *)&vwarn,
  (void *)&vwarnx,
  (void *)&vwprintf,
  (void *)&vwscanf,
  (void *)&wait,
  (void *)&wait3,
  (void *)&wait4,
  (void *)&waitid,
  (void *)&waitpid,
  (void *)&warn,
  (void *)&warnx,
  (void *)&wcrtomb,
  (void *)&wcscat,
  (void *)&wcschr,
  (void *)&wcscmp,
  (void *)&wcscoll,
  (void *)&wcscpy,
  (void *)&wcscspn,
  (void *)&wcsftime,
  (void *)&wcslen,
  (void *)&wcsncat,
  (void *)&wcsncmp,
  (void *)&wcsncpy,
  (void *)&wcspbrk,
  (void *)&wcsrchr,
  (void *)&wcsrtombs,
  (void *)&wcsspn,
  (void *)&wcsstr,
  (void *)&wcstod,
  (void *)&wcstof,
  (void *)&wcstoimax,
  (void *)&wcstok,
  (void *)&wcstol,
  (void *)&wcstold,
  (void *)&wcstoll,
  (void *)&wcstombs,
  (void *)&wcstoul,
  (void *)&wcstoull,
  (void *)&wcstoumax,
  (void *)&wcsxfrm,
  (void *)&wctob,
  (void *)&wctomb,
  (void *)&wctrans,
  (void *)&wctype,
  (void *)&wmemchr,
  (void *)&wmemcmp,
  (void *)&wmemcpy,
  (void *)&wmemmove,
  (void *)&wmemset,
  (void *)&wprintf,
  (void *)&write,
  (void *)&writev,
  (void *)&wscanf,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  (void *)&asctime,
  (void *)&asctime_r,
  0,
  (void *)&chdir,
  (void *)&chown,
  (void *)&close,
  (void *)&creat,
  (void *)&creat64,
  (void *)&ctime,
  (void *)&ctime_r,
  (void *)&daylight,
  (void *)&difftime,
  (void *)&endpwent,
  0,
  0,
  0,
  0,
  0,
  0,
  (void *)&execl,
  (void *)&execle,
  (void *)&execlp,
  (void *)&execv,
  (void *)&execve,
  (void *)&execvp,
  (void *)&execvpe,
  0,
  0,
  (void *)&fchown,
  0,
  0,
  0,
  (void *)&fork,
  (void *)&fstat,
  (void *)&fstat64,
  0,
  0,
  (void *)&getegid,
  (void *)&geteuid,
  (void *)&getgid,
  (void *)&getgrgid,
  (void *)&getgrnam,
  (void *)&getgrouplist,
  (void *)&getgroups,
  0,
  0,
  0,
  0,
  (void *)&getpriority,
  0,
  0,
  (void *)&getpwnam,
  (void *)&getpwnam_r,
  (void *)&getpwuid,
  (void *)&getpwuid_r,
  0,
  0,
  (void *)&getuid,
  (void *)&gmtime,
  (void *)&gmtime_r,
  0,
  (void *)&lchown,
  (void *)&localtime,
  (void *)&localtime_r,
  (void *)&lstat,
  (void *)&lstat64,
  (void *)&memcmp,
  0,
  (void *)&mkdir,
  0,
  (void *)&mkdtemp,
  (void *)&mknod,
  (void *)&mktime,
  (void *)&open,
  (void *)&open64,
  0,
  (void *)&opendir,
  (void *)&poll,
  0,
  (void *)&pthread_attr_init,
  (void *)&pthread_create,
  0,
  (void *)&rmdir,
  0,
  (void *)&setegid,
  (void *)&seteuid,
  (void *)&setgid,
  (void *)&setgroups,
  (void *)&setpriority,
  (void *)&setregid,
  0,
  0,
  (void *)&setreuid,
  (void *)&setuid,
  (void *)&stat,
  (void *)&stat64,
  (void *)&statvfs,
  (void *)&strcasestr,
  (void *)&strftime,
  0,
  0,
  (void *)&timegm,
  (void *)&timelocal,
  (void *)&timezone,
  (void *)&ttyname,
  (void *)&ttyname_r,
  (void *)&tzname,
  (void *)&tzset,
  0,
  0,
  0
};
